config husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,20 +12,20 @@ echo '🏗️👷 Styling, testing and building your project before committing'
 # )
 
 # Check ESLint Standards
-npm run lint ||
+pnpm run lint ||
 (
         echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
         false; 
 )
 
-# # Check tsconfig standards
-# npm run check-types ||
-# (
-#     echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
-#             Are you seriously trying to write that? Make the changes required above.'
-#     false;
-# )
+# Check tsconfig standards
+pnpm run check-types ||
+(
+    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
+            Are you seriously trying to write that? Make the changes required above.'
+    false;
+)
 
 # If everything passes... Now we can commit
 # echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
